# Generated by Django 2.1.7 on 2019-03-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAcademico',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Emaisl acadêmicos',
                'db_table': 'email_academico',
            },
        ),
    ]
